"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['pswd_mgr_pysim5.py']
DATA_FILES = []
OPTIONS = {'iconfile': '/Users/michaelpauken/Downloads/Downloads_images/password.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
